services:
  # Emory Hacks 2025 Spring (static)
  - type: web
    name: emory-hacks-2025-spring
    runtime: static
    repo: https://github.com/project-emory/emory-hacks
    branch: "2025/spring"
    buildCommand: npm ci; npm run build
    staticPublishPath: out
    autoDeployTrigger: commit

  # Emory Hacks 2025 Fall (static)
  - type: web
    name: emory-hacks-2025-fall
    runtime: static
    repo: https://github.com/project-emory/emory-hacks
    branch: "2025/fall"
    buildCommand: pnpm i; pnpm build
    staticPublishPath: out
    autoDeployTrigger: commit
