services:
services:
  - type: web
    name: emory-hacks
    runtime: static
    plan: free
    buildCommand: npm ci; npm run build
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080