services:
  # Emory Hacks 2025 Spring
  - type: web
    name: emory-hacks-2025-spring
    runtime: static
    repo: https://github.com/project-emory/emory-hacks
    branch: "2025/spring"
    buildCommand: npm ci; npm run build
    staticPublishPath: out
    autoDeployTrigger: commit

  # Emory Hacks 2025 Fall
  - type: web
    name: emory-hacks-2025-fall
    runtime: node
    repo: https://github.com/project-emory/emory-hacks
    branch: "2025/fall"
    plan: free
    envVars:
      - fromGroup: google-api
    region: oregon
    buildCommand: npm ci; npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    domains:
      - emoryhacks.com
version: "1"
